### PR TITLE
1.17 (hopefully)

### PR DESCRIPTION
**Pull request by Fourmisain**
- hopefully fix the `QueryResponseS2CPacket` mixin:

Use `@ModifyArg` on the second argument of the `deserialize` call to effectively save the stringified JSON in a local variable, let the constructor do it's thing (setting `metadata`), then execute `parseMinepkgMetadata` (using the stringified JSON).

- update gradle wrapper
- update shadow version
- set mixin compatibility level to Java 16

**Untested** but at least it doesn't directly crash anymore!

### CODE REVIEW

**Comment by fiws** [comment]
thanks a lot! it looks like this is working fine.

anything you wanted to still change because this is a WIP? or was it only because it was untested?

if it's consider done otherwise i would kindly request that you add a few comments to the code you have added (explaining what they do and maybe why they are needed. your PR mostly explains that already). that would be awesome

**Comment by Fourmisain** [comment]
> anything you wanted to still change because this is a WIP? or was it only because it was untested?

Nope, just because it was untested.

> i would kindly request that you add a few comments to the methods you have added (explaining what they do and maybe why they are needed)

I thought it was pretty straight-forward, but I'll explain it in detail - since I'm not sure what exactly you're looking for from a comment, it's probably better if you add them yourself.

So the issue was that the previous `read` method turned into a constructor with 1.17 and `@Overwrite` doesn't work with constructors.

For reference, the constructor looks like this:
```
public QueryResponseS2CPacket(PacketByteBuf buf) {
    this.metadata = (ServerMetadata)JsonHelper.deserialize(GSON, buf.readString(32767), ServerMetadata.class);
}
```

We need the value of `buf.readString(32767)` and since it mutates `buf`, we can't simply execute it twice so we need to somehow "capture" the value inside the constructor.
That's done with the `@ModifyArg`, which is basically an injected method call (here called `captureJSON`) around one specified method call parameter and the one we want is the second parameter (`index = 1`) of `JsonHelper.deserialize`.
So imagine the constructor now looks like
```
public QueryResponseS2CPacket(PacketByteBuf buf) {
    this.metadata = (ServerMetadata)JsonHelper.deserialize(GSON, captureJSON(buf.readString(32767)), ServerMetadata.class);
}
```
All `captureJSON` does is safe the value to the `stringifiedJSON` field (which is `@Unique`, meaning it never overwrites a field) and return the same value.

The rest is just taking everything that was in `read`, making it use `stringifiedJSON` and putting it into `parseMinepkgMetadata`, which is injected at `"RETURN"`, so at the very end of the constructor, so imagine it looking like
```
public QueryResponseS2CPacket(PacketByteBuf buf) {
    this.metadata = (ServerMetadata)JsonHelper.deserialize(GSON, captureJSON(buf.readString(32767)), ServerMetadata.class);
    parseMinepkgMetadata();
}
```


P.S. The reason I removed the `// Copies this final property from the original class` comment is because nothing is being copied, `@Shadow` allows to access the very same field of the mixed in class.

P.P.S Thinking about this, maybe a cancelable `@Inject` at `"HEAD"` would have worked to directly replace the previous `@Overwrite` - I would find it odd if it did though.

**Comment by Fourmisain** [comment]
Added some comments, better than nothing I guess.

**Comment by fiws** [comment]
thanks for explaining & commenting. i did not understand everything but it's good to have it in case someone needs to lookup what this does again.

**Pull request merged**
